name: Build Installers

on:
  push:
    # branches-ignore:
    #   - master
    #   - dev
  workflow_dispatch:

jobs:
  windows-installer:
    name: Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Installer
      run: docker run -v docker:/src/ danleyb2/pyinstaller-windows "pyinstaller platerec_installer.spec -F"
    - uses: actions/upload-artifact@v2
      with:
        name: WindowsInstaller
        path: docker/dist/PlateRecognizer-Installer.exe

  linux-installer:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Installer
      run: docker run -v docker:/src/ cdrx/pyinstaller-linux "pyinstaller platerec_installer.spec -F"
    - uses: actions/upload-artifact@v2
      with:
        name: WindowsInstaller
        path: docker/dist/PlateRecognizer-Installer
